migrated to vertx 3.4.1

diff --git a/backgammon-vertx/ceylonb b/backgammon-vertx/ceylonb
--- a/backgammon-vertx/ceylonb
+++ b/backgammon-vertx/ceylonb
@@ -37,6 +37,14 @@ else
     JAVA="$JAVA_HOME/bin/java"
 fi
 
+# Make sure we have java installed
+if ! hash java 2>&-
+then
+    echo >&2 "Java not found, you must install Java in order to compile and run Ceylon programs"
+    echo >&2 "Go to http://www.java.com/getjava/ to download the latest version of Java"
+    exit 1
+fi
+
 #JAVA_DEBUG_OPTS="-Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y"
 
 if [ "$PRESERVE_JAVA_OPTS" != "true" ]; then
